version: "3"

services:
  api:
    image: api
    build: ./backend
    environment: 
      - MONGO_URI=172.17.0.1
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - 8000:8080

  mongo:
    image: mongo
    command: mongod --bind_ip 172.17.0.1
    ports:
      - 27017:27017
