version: "3"

services:
  frontend:
    image: nginx
    volumes:
      - "frontend/dist:/var/www/vorona.gg/html"
      - "/etc/letsencrypt"
    ports:
      - 443:443

  api:
    image: api
    build: ./backend
    environment: 
      - MONGO_URI=host.docker.internal
    volumes:
      - "/etc/letsencrypt"
    ports:
      - 8000:8080

  mongo:
    image: mongo
    command: mongod --bind_ip 0.0.0.0
    ports:
      - 27017:27017
