version: "3"

services:
  frontend:
    image: frontend
    build: ./frontend
    volumes:
      - "./frontend:/usr/src/frontend"
    ports:
      - 5000:8080
      
  api:
    image: api
    build: ./backend
    environment: 
      - MONGO_URI=host.docker.internal
      - DEV_ENV=true
    ports:
      - 8000:8080

  mongo:
    image: mongo
    command: mongod --bind_ip 0.0.0.0
    volumes:
      - "mongo:/data/db"
    ports:
      - 27017:27017

volumes:
  mongo:
    external: yes