version: "3"

services:
  frontend:
    image: frontend
    build: ./frontend
    volumes:
      - "./frontend:/usr/src/frontend"
    ports:
      - 5000:8080
      
  api:
    image: api
    depends_on:
      - postgres
    build: ./backend
    environment: 
      - POSTGRES_URI=postgres://postgres:$POSTGRES_PASSWORD@postgres:5432/vorona
      - DEV_ENV=true
    ports:
      - 8000:8080

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

volumes:
  postgres:
    external: yes